SAMPLES = ['Sample1', 'Sample2', 'Sample3']



rule all:
    input:
        'results/collated.txt'


rule quantify_genes:
    input:
        genome = 'data/genome.fa',
        r1 = 'data/{sample}.R1.fastq.gz',
        r2 = 'data/{sample}.R2.fastq.gz'

    output:
        'quantified/{sample}.txt'
    shell:
        'echo {input.genome} {input.r1} {input.r2} > {output}'


rule collate_outputs:
    input:
        expand('quantified/{sample}.txt', sample=SAMPLES)
    output:
        'results/collated.txt'
    run:
        with open(output[0], 'w') as out:
            for i in input:
                print(f"output: {i}")
                sample = i.split('.')[0]
                for line in open(i):
                    out.write(sample + ' ' + line)


rule clean:
    shell:
        'rm quantified/*.txt'